# Generated by Django 5.0.2 on 2024-03-02 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_exercise', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseDataList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sets', models.CharField(max_length=50)),
                ('gif', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('name_of_parts_exercise', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_list', to='core.exerciselist')),
            ],
        ),
    ]
