# Generated by Django 5.0.2 on 2024-03-02 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_exerciselist_exercisedatalist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciselist',
            old_name='name_of_exercise',
            new_name='name_of_day',
        ),
    ]
