# Generated by Django 5.0.2 on 2024-03-02 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_name_of_exercise_exerciselist_name_of_day'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExerciseList',
            new_name='ExerciseDay',
        ),
    ]
