# Generated by Django 5.0.2 on 2024-03-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_exerciselist_exerciseday'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisedatalist',
            name='name_of_exercise',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
