# Generated by Django 5.0.2 on 2024-03-12 19:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_exercise_reps_set_useractivity_workout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
