# Generated by Django 5.0.2 on 2024-03-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_set_date_alter_workout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
