# Generated by Django 5.0.2 on 2024-03-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_bmirecord_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseday',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
